// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmTLl5YH6rpiFoOKsaHv-G5OPYu5NwDtU',
    appId: '1:850310345041:web:fef5a91931b69773f66370',
    messagingSenderId: '850310345041',
    projectId: 'jokes-app-cccbc',
    authDomain: 'jokes-app-cccbc.firebaseapp.com',
    storageBucket: 'jokes-app-cccbc.firebasestorage.app',
    measurementId: 'G-PQWG28GTHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsobZN5h5SxokMJ3HrsdbNQxUDSJ8Vd30',
    appId: '1:850310345041:android:793e6e66da345193f66370',
    messagingSenderId: '850310345041',
    projectId: 'jokes-app-cccbc',
    storageBucket: 'jokes-app-cccbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyoFtC-M6FOoBuqN1dn4fY1RAX3PnQys',
    appId: '1:850310345041:ios:978a48971702b953f66370',
    messagingSenderId: '850310345041',
    projectId: 'jokes-app-cccbc',
    storageBucket: 'jokes-app-cccbc.firebasestorage.app',
    iosBundleId: 'com.example.jokesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATyoFtC-M6FOoBuqN1dn4fY1RAX3PnQys',
    appId: '1:850310345041:ios:978a48971702b953f66370',
    messagingSenderId: '850310345041',
    projectId: 'jokes-app-cccbc',
    storageBucket: 'jokes-app-cccbc.firebasestorage.app',
    iosBundleId: 'com.example.jokesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmTLl5YH6rpiFoOKsaHv-G5OPYu5NwDtU',
    appId: '1:850310345041:web:f2132738eb235f4bf66370',
    messagingSenderId: '850310345041',
    projectId: 'jokes-app-cccbc',
    authDomain: 'jokes-app-cccbc.firebaseapp.com',
    storageBucket: 'jokes-app-cccbc.firebasestorage.app',
    measurementId: 'G-RFGGXKPP9Y',
  );
}
